name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        nginx_version: [ 1.30.4 ]
        script_name: [ '','-debug']
    runs-on: ubuntu-latest
    name: "Test build nginx${{matrix.script_name}} ${{ matrix.nginx_version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install environment
        run: 'sudo apt install -y libpcre2-dev zlib1g-dev wget'
      - name: Build nginx${{matrix.script_name}} ${{ matrix.nginx_version }}
        env:
            NGINX_VERSION: "${{ matrix.nginx_version }}"
            VTS_MODULE_VERSION: "0.0.2"
            STS_MODULE_VERSION: "0.0.3"
            DYNAMIC_HEALTHCHECK_MODULE_VERSION: "0.0.5"
        run: './build${{matrix.script_name}}.sh'
